-- Crea la tabla de estanterías
CREATE TABLE IF NOT EXISTS RACKS (
    ID            INT      NOT NULL,
    WAREHOUSE_ID  INT      NOT NULL,
    UUID          CHAR(36) NOT NULL,
    TYPE          CHAR(1)  NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RACK_WAREHOUSE
      FOREIGN KEY (WAREHOUSE_ID)
      REFERENCES WAREHOUSES(ID)
);